version: '2'
volumes:
  data: {}
  data_db: {}

services:
  nginx:
    container_name: nginx
    restart:
      always
    tty: true
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - data:/var/www/html/

  mariadb:
    container_name: mariadb
    restart:
      always
    tty: true
    build: ./requirements/mariadb
    expose:
      - "3306"
    env_file:
      - .env
    # the m1 has a host volumes mount issue
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    restart:
      always
    tty: true
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    # env_file can skip
    env_file:
      - .env
    volumes:
      - data:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge
