version: '2'

volumes:
  db: {}

services:
  nginx:
    container_name: nginx
    restart:
      always
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ${WP}:/var/www/html/
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    # restart: unless-stopped
    build: ./requirements/mariadb
    expose:
      - "3306"
    env_file:
      - .env
    # the m1 has a host volumes mount issue
    volumes:
      - ${DB}:/var/lib/mysql
    networks:
      - inception

  wordpress:
    restart:
      always
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ${WP}:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge
